### ISSUE TITLE
fix cart state

### ISSUE THREAD

**Issue by lizzthabet** [grace-shopper-ridl/ridl#122]
the `initialState` in the cart store uses an `orderId`, but when the cart is updated from any action, it's set as `id`. the `initialState` needs to be updated to reflect how the cart id is updated later.

**Comment by lizzthabet** [comment]
@impomales, this is the issue i was describing for reference!

**Comment by impomales** [comment]
@lizzthabet I tried changing initial state to use just id, and the error was still there. I think I know what the issue is...just want to make sure I don't break anything.
